# Copyright 2025 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
OPD Teacher Server for computing log probabilities on student trajectories.

This server uses vLLM to efficiently compute full log probability distributions
for sequences generated by the student model. It runs independently with its own
TP/PP settings and GPU allocation.
"""

import argparse
import logging

import torch
import zmq
from vllm import LLM

try:
    from .utils import deserialize, serialize
except ImportError:
    from utils import deserialize, serialize

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class OPDTeacherServer:
    """Server for computing teacher log probabilities for OPD.

    This server loads a teacher model using vLLM and computes full log probability
    distributions for input sequences. Unlike generation, it computes logprobs for
    existing sequences (teacher-forcing mode).

    Args:
        model_path (str): Path to teacher model checkpoint
        port (int): Port to listen on for client connections
        tensor_parallel_size (int): Tensor parallelism degree (default: 1)
        gpu_memory_utilization (float): Fraction of GPU memory to use (default: 0.9)
        dtype (str): Model dtype (default: "bfloat16")
        max_model_len (int): Maximum sequence length (default: None, use model config)
        trust_remote_code (bool): Whether to trust remote code (default: False)
    """

    def __init__(
        self,
        model_path: str,
        port: int = 15555,
        tensor_parallel_size: int = 1,
        gpu_memory_utilization: float = 0.9,
        dtype: str = "bfloat16",
        max_model_len: int = None,
        trust_remote_code: bool = False,
    ):
        self.port = port

        logger.info(f"Loading OPD teacher model from {model_path}")
        logger.info(f"TP={tensor_parallel_size}, GPU mem={gpu_memory_utilization}, dtype={dtype}")

        # Initialize vLLM engine
        self.llm = LLM(
            model=model_path,
            tensor_parallel_size=tensor_parallel_size,
            gpu_memory_utilization=gpu_memory_utilization,
            dtype=dtype,
            max_model_len=max_model_len,
            trust_remote_code=trust_remote_code,
            enforce_eager=True,  # Disable CUDA graphs for logprob computation
        )

        self.tokenizer = self.llm.get_tokenizer()
        logger.info(f"Teacher model loaded successfully, vocab_size={len(self.tokenizer)}")

        # Setup ZeroMQ server
        self.context = zmq.Context()
        self.socket = self.context.socket(zmq.REP)

        # Set socket options to allow immediate rebind after restart
        self.socket.setsockopt(zmq.LINGER, 0)  # Don't wait for pending messages on close

        try:
            self.socket.bind(f"tcp://*:{port}")
            logger.info(f"OPD Teacher server listening on port {port}")
        except zmq.error.ZMQError as e:
            if "Address already in use" in str(e):
                logger.error(f"Port {port} is already in use.")
                logger.error("Try: 1) Wait 30 seconds for kernel to release port, or")
                logger.error("     2) Find process with: netstat -tlnp | grep {port}")
                logger.error("     3) Kill process with: kill -9 <PID>")
                raise
            else:
                raise

    def compute_logprobs(self, input_ids: list[list[int]], attention_mask: list[list[int]]) -> list[torch.Tensor]:
        """Compute log probabilities for the tokens in each sequence using vLLM.

        For K2 KL estimator, we only need the teacher's logprob of each token given its context.

        Args:
            input_ids (list[list[int]]): List of input ID sequences (student's generated sequences)
            attention_mask (list[list[int]]): List of attention masks

        Returns:
            list[torch.Tensor]: List of log probability tensors, each of shape [seq_len-1]
                                (logprob of each token given previous context)
        """
        batch_size = len(input_ids)
        all_logprobs = []

        # Process each sequence
        for i in range(batch_size):
            ids = input_ids[i]
            mask = attention_mask[i]

            # Filter to valid tokens only (where mask==1)
            if isinstance(mask[0], bool):
                valid_ids = [token_id for token_id, m in zip(ids, mask) if m]
            else:
                valid_ids = [token_id for token_id, m in zip(ids, mask) if m > 0]

            if len(valid_ids) <= 1:
                # Need at least 2 tokens to compute logprobs (input -> prediction)
                all_logprobs.append(torch.zeros(0, dtype=torch.float32))
                continue

            try:
                # Use vLLM to compute prompt logprobs
                from vllm import SamplingParams

                sampling_params = SamplingParams(
                    temperature=0.0,
                    max_tokens=1,  # We only care about prompt logprobs
                    prompt_logprobs=1,  # Get logprob for the actual next token
                )

                # vLLM 0.10.0+ API: pass prompt_token_ids in prompts parameter
                outputs = self.llm.generate(
                    prompts=[{"prompt_token_ids": valid_ids}], sampling_params=sampling_params, use_tqdm=False
                )

                # Extract prompt logprobs
                output = outputs[0]
                prompt_logprobs = output.prompt_logprobs

                if prompt_logprobs is None:
                    logger.warning(f"No prompt logprobs returned for sequence {i}")
                    all_logprobs.append(torch.zeros(len(valid_ids) - 1, dtype=torch.float32))
                    continue

                # Extract logprob of each token
                # prompt_logprobs[j] contains logprobs for predicting token j (given tokens 0:j-1)
                # We want logprobs for tokens [1:seq_len] given their context
                token_logprobs = []
                for pos in range(1, len(valid_ids)):  # Start from position 1 (skip first token, no context)
                    if prompt_logprobs[pos] is not None:
                        # Get the logprob for the actual token at this position
                        actual_token_id = valid_ids[pos]
                        if actual_token_id in prompt_logprobs[pos]:
                            logprob = prompt_logprobs[pos][actual_token_id].logprob
                        else:
                            # Token not in returned logprobs, use very low probability
                            logger.warning(
                                f"Token {actual_token_id} not in prompt_logprobs at position {pos}, using default"
                            )
                            logprob = -100.0  # Very low logprob
                        token_logprobs.append(logprob)
                    else:
                        token_logprobs.append(0.0)

                all_logprobs.append(torch.tensor(token_logprobs, dtype=torch.float32))

            except Exception as e:
                logger.error(f"Error computing logprobs for sequence {i}: {e}")
                import traceback

                traceback.print_exc()
                # Return zeros on error
                all_logprobs.append(torch.zeros(len(valid_ids) - 1, dtype=torch.float32))

        return all_logprobs

    def serve(self):
        """Main server loop to handle client requests."""
        logger.info("OPD Teacher server ready to handle requests")

        while True:
            try:
                # Receive request
                message = self.socket.recv()
                request = deserialize(message)

                # Extract input_ids and attention_mask
                input_ids = request.get("input_ids")
                attention_mask = request.get("attention_mask")

                if input_ids is None or attention_mask is None:
                    response = {"status": "error", "reason": "Missing input_ids or attention_mask"}
                    self.socket.send(serialize(response))
                    continue

                # Compute logprobs
                logger.info(f"Computing logprobs for {len(input_ids)} sequences")
                logprobs = self.compute_logprobs(input_ids, attention_mask)

                # Send response
                response = {"status": "success", "logprobs": logprobs}
                self.socket.send(serialize(response))
                logger.info(f"Sent logprobs for {len(logprobs)} sequences")

            except KeyboardInterrupt:
                logger.info("Shutting down OPD Teacher server")
                break
            except Exception as e:
                logger.error(f"Error handling request: {e}")
                response = {"status": "error", "reason": str(e)}
                try:
                    self.socket.send(serialize(response))
                except Exception:
                    pass

    def __del__(self):
        """Cleanup on server shutdown."""
        if hasattr(self, "socket"):
            self.socket.close()
        if hasattr(self, "context"):
            self.context.destroy()


def main():
    parser = argparse.ArgumentParser(description="OPD Teacher Server for computing log probabilities")
    parser.add_argument("--model_path", type=str, required=True, help="Path to teacher model checkpoint")
    parser.add_argument("--port", type=int, default=15555, help="Port to listen on")
    parser.add_argument("--tp", type=int, default=1, help="Tensor parallel size")
    parser.add_argument("--gpu_memory_utilization", type=float, default=0.9, help="GPU memory utilization")
    parser.add_argument("--dtype", type=str, default="bfloat16", help="Model dtype")
    parser.add_argument("--max_model_len", type=int, default=None, help="Maximum model length")
    parser.add_argument("--trust_remote_code", action="store_true", help="Trust remote code")

    args = parser.parse_args()

    server = OPDTeacherServer(
        model_path=args.model_path,
        port=args.port,
        tensor_parallel_size=args.tp,
        gpu_memory_utilization=args.gpu_memory_utilization,
        dtype=args.dtype,
        max_model_len=args.max_model_len,
        trust_remote_code=args.trust_remote_code,
    )

    server.serve()


if __name__ == "__main__":
    main()
